# wrangler.toml (最终正确版)

# Worker 的名称，与 Cloudflare 仪表盘上的名称完全一致
name = "joeynews"

# 主入口文件
main = "_worker.js"

# 兼容性日期
compatibility_date = "2025-09-08"

# ======================= 这是最终的正确修复 =======================
# no_bundle = true 是一个顶级配置，它告诉 Wrangler：
# “main 字段指向的 _worker.js 是一个已经完成的独立文件，
#  不要对它进行任何构建、打包或依赖分析，直接将它上传。”
# 这将彻底绕过导致错误的代码检查步骤。
no_bundle = true
# =============================================================
