# 工作流名称
name: Sync and Rename Worker Script

# 工作流触发器
on:
  # 允许在 GitHub 的 Actions 页面手动触发此工作流
  workflow_dispatch:
  
  # 定时任务：设置为每天的国际标准时间（UTC）凌晨2点运行
  schedule:
    - cron: '0 2 * * *'

# 定义工作任务
jobs:
  sync:
    # 使用最新的 Ubuntu 虚拟环境来运行任务
    runs-on: ubuntu-latest

    # =======================================================
    # V V V V V V V V V V V V V V V V V V V V V V V V V V V V V
    #
    # 添加此部分以授予工作流写入仓库的权限
    permissions:
      contents: write
    #
    # ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^
    # =======================================================
    
    # 任务包含的步骤
    steps:
      # 步骤1: 检出（Checkout）你的仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤2: 下载 "少年你相信光吗" 文件并重命名为 "_worker.js"
      - name: Download and rename script
        run: |
          curl -L -o ./_worker.js "https://raw.githubusercontent.com/byJoey/cfnew/main/%E5%B0%91%E5%B9%B4%E4%BD%A0%E7%9B%B8%E4%BF%A1%E5%85%89%E5%90%97"

      # 步骤3: 检查文件是否有变动，如果有，则自动提交并推送到你的仓库
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "CI: Update and rename worker script to _worker.js"
          file_pattern: _worker.js
